name:                jsortkeys
version:             0.0.0.0
github:              "carymrobbins/jsortkeys"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 Cary Robbins"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/carymrobbins/jsortkeys#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- text

executables:
  jsortkeys:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
